### ISSUE TITLE
How could i run this code with openai  api, The OpenAI API does not support Guidance pattern controls.

### ISSUE THREAD

**Issue by Marklong123** [QuangBK/generativeAgent_LLM#2]

**Comment by QuangBK** [comment]
The goal of this repo is to implement Generative Agen with local LLMs. Since I don't have a chance to use the OpenAI API, I cannot answer your question. I only recommend checking whether Guidance can support all the features with OpenAI API, [like this](https://github.com/microsoft/guidance/blob/main/README.md#live-streaming-notebook).
