### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by chris-aeviator** [QuangBK/generativeAgent_LLM#7]
Did you start working on the idea of the "simulation loop"? What I don't get from the paper (where they also have spatial movement): is there a world-state including a world tick, or how would the loop look like, do agents decide what to do next (reflect, obsever, ...) or is this a pre-programmed script when implemented.

![grafik](https://github.com/QuangBK/generativeAgent_LLM/assets/11522213/b493343a-70ef-419b-855f-58ad41432c7b)

**Comment by QuangBK** [comment]
Hi, for making the one like the original paper, we need to have a simulation environment (they did with Phaser) so the agents can interact with it. In my implementation, only the agent functions are provided but not the 'loop logic' (since I don't have the environment).
Hope that someone can make a simulation environment for it :)
